language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# command to install dependencies
install:
  - pip install .[ci]

# command to run tests
script:
  - pytest -sv --cov=plsmake plsmake/tests/
  - codecov
